### ISSUE TITLE
Certificate outdated

### ISSUE THREAD

**Issue by Sungamm** [primus852/deutsche-feiertage-api#2]
Hey good Mornig,

thank you for the great service. I used your service to implement into a Apple Automation to find out its a bank holiday or not. 

But your server certificate is out of date and therefore the Automation did not work anymore. 

Any chance to prolong the certificate for deutsche-Feiertage-api.de?

**Comment by primus852** [comment]
Good morning!

Thanks for your hint, I renewed the certificate, everything should be back
to normal!

cheers,

Torsten

Am Di., 16. Juni 2020 um 09:49 Uhr schrieb Sungamm <notifications@github.com

**Comment by Sungamm** [comment]
Thank you for your prompt help!
