### ISSUE TITLE
Einige Feiertage fehlen (2020)

### ISSUE THREAD

**Issue by mkoentopf** [primus852/deutsche-feiertage-api#3]
Da es sich hier um ein deutsches Projekt handelt, schreibe ich in Deutsch.

Ich vermisse aktuell 4 Feiertage in der Datenbank.
Ich beziehe mich hierbei auf den folgenden Wikipedia-Artikel:
https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland

- 8. August - Augsburger Hohes Friedensfest
- 15. August - Mariä Himmelfahrt
- 20. September - Weltkindertag
- 1. November - Allerheiligen

Können die integriert werden?

**Comment by primus852** [comment]
Danke für den Hinweis.
- Weltkindertag (ur Thüringen) hinzugefügt
- Allerheiligen (Baden-Würtemberg, Bayer, Nordrhein-Westphalen, Rheinland-Pfalz, Saarland) hinzugefügt

Die anderen beiden sind etwas schwierig:
- Augsburger Hohes Friedensfest: Dies gilt nur im Kreis um Augsburg, die API kann allerdings nur Bundesländer abbilden
- Mariä Himmelfahrt: Ähnlich, Zitat Wikipedia: Mariä Himmelfahrt ist in Bayern in den derzeit 1704 [...] Gemeinden mit überwiegend katholischer Bevölkerung gesetzlicher Feiertag, in den restlichen 352 [...] Gemeinden nicht
