### ISSUE TITLE
No server found

### ISSUE THREAD

**Issue by Sungamm** [primus852/deutsche-feiertage-api#4]
Good Morning,

I used your api access to have a small Apple shortcut running. Its extrem helpful that shutter will open later if a holiday. Thank you for your work and sharing.

I tried to modify the shortcut but I receive the message "Es wurde kein Server mit dem angegebenen Hostnamen gefunden" - no Server found.

https://deutsche-feiertage-api.de/api/v1/[aktuelles Datum]

Is the server only temporary down and I have a bad timming or is there a general issue?

best regards
Magnus

**Comment by primus852** [comment]
Dear Magnus,

the server seems to be up and running, I just checked with POSTMan:

![grafik](https://user-images.githubusercontent.com/5185509/116856604-b8c52180-abfb-11eb-8a01-6953b6bf752c.png)
Can you try again?

**Comment by Sungamm** [comment]
Hi Primus,

Thank you for your fast response!

I tried again and server is not available. I switched off WLAN and use mobile connection with same result. 




...von unterwegs gesendet.

**Comment by primus852** [comment]
Please let me know what request you sent

**Comment by Sungamm** [comment]
I assume it’s a glitch in Apple HomeKit shortcut. 

If I run the native shortcut I build I got a response from server. But if I run the automatic with that kind of shortcut build in, I have the error „no Server found“. Crazy nothing change on my side. Maybe update to iOS 14.5. 

But server is running und working fine. Thank you again for your prompt feedback and friendly help. 



...von unterwegs gesendet.

**Comment by Sungamm** [comment]
Server is working. It’s a problem on my side. Thank you for great help!
